export const apiStatusType = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  REDIRECTION: 3,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  INTERNAL_SERVER_ERROR: 500,
}

export const answerType = Object.freeze({
  TRUE: 'TRUE',
  FALSE: 'FALSE',
})
